document.addEventListener('DOMContentLoaded',()=>{
 const messages=document.getElementById('chat-messages'),input=document.getElementById('chat-input'),send=document.getElementById('btn-send');
 const keyInput=document.getElementById('ai-key'),status=document.getElementById('ai-status')||(() =>{
  // Crée un badge discret si l'ancien a été retiré (PDF)
  const b=document.createElement('div');
  b.id='ai-status';
  b.style.cssText='position:absolute;top:8px;right:12px;padding:4px 8px;border-radius:999px;font-size:10px;font-weight:800;z-index:10';
  const host=document.querySelector('.assistant-main')||document.body;
  host.style.position='relative';
  host.prepend(b);
  return b;
})(),listen=document.getElementById('btn-listen'),mic=document.getElementById('btn-mic'),micStatus=document.getElementById('mic-status'),voiceSelect=document.getElementById('voice-select'),voiceTest=document.getElementById('voice-test');
 const zones=Object.fromEntries(ZONES_GEOJSON.features.map(f=>[f.properties.nom.toLowerCase(),f.properties])); const mission=MISSIONS_DATA.derniere_mission; const zoneList=ZONES_GEOJSON.features.map(f=>f.properties);
 const clean=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');let lastBot='';
 try{ if(keyInput) { keyInput.value=localStorage.getItem('agrivision_groq_key')||''; setStatus(); keyInput.addEventListener('input',()=>{const k=keyInput.value.trim();k?localStorage.setItem('agrivision_groq_key',k):localStorage.removeItem('agrivision_groq_key');setStatus()}); } else { setStatus(); } }catch(e){} 
 function setStatus(){ try{ const val = (keyInput && keyInput.value) ? keyInput.value.trim() : (localStorage.getItem('agrivision_groq_key')||''); const on=val.length>15; if(status){status.textContent=on?'IA avancée · en ligne':'Guide simple · hors ligne';status.className=on?'badge-ok':'badge-warn'} }catch(e){ if(status){status.textContent='Guide simple · hors ligne';status.className='badge-warn'} } }
 let availableVoices=[];function loadVoices(){if(!('speechSynthesis'in window))return;availableVoices=speechSynthesis.getVoices().filter(v=>v.lang.toLowerCase().startsWith('fr'));const saved=sessionStorage.getItem('agrivision_voice')||'';voiceSelect.innerHTML='<option value="">Meilleure voix française disponible</option>'+availableVoices.map(v=>`<option value="${v.name.replace(/"/g,'&quot;')}">${v.name} — ${v.lang}</option>`).join('');voiceSelect.value=availableVoices.some(v=>v.name===saved)?saved:''}loadVoices();if('speechSynthesis'in window)speechSynthesis.onvoiceschanged=loadVoices;voiceSelect.addEventListener('change',()=>sessionStorage.setItem('agrivision_voice',voiceSelect.value));
 function bestVoice(){if(voiceSelect.value)return availableVoices.find(v=>v.name===voiceSelect.value);const preferred=/(natural|neural|google|microsoft|amelie|amélie|denise|audrey|marie|thomas)/i;return availableVoices.find(v=>preferred.test(v.name))||availableVoices[0]}
 function speak(t){ if(window.AgriAudio){ window.AgriAudio.speak(t, {lang:'fr-FR', rate:0.92}); return; } if(!('speechSynthesis' in window)) return alert('La lecture vocale n’est pas disponible sur cet appareil.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='fr-FR';u.rate=.92;u.pitch=1;const v=bestVoice();if(v)u.voice=v;speechSynthesis.speak(u)}
 function add(role,value,thinking=false){const d=document.createElement('div');d.className='msg '+(role==='user'?'msg-user':'msg-bot')+(thinking?' thinking':'');d.textContent=value;if(role==='bot'&&!thinking){lastBot=value;const b=document.createElement('button');b.className='msg-speak';b.textContent='🔊 Lire cette réponse';b.addEventListener('click',()=>speak(value));d.appendChild(b)}messages.appendChild(d);messages.scrollTop=messages.scrollHeight;return d}
 function setBot(el,value){el.textContent=value;el.classList.remove('thinking');lastBot=value;const b=document.createElement('button');b.className='msg-speak';b.textContent='🔊 Lire cette réponse';b.addEventListener('click',()=>speak(value));el.appendChild(b)}
 function zoneText(z){const etat=z.risque==='faible'?'les plantes paraissent plus vigoureuses':'la vigueur est plus faible que dans la zone verte';return `${z.nom}\n\nCe que la carte montre : ${etat}.\nValeur VARI : ${z.vari}. Surface indiquée : ${z.surface_ha} hectare.\n\nCe que vous devez faire : ${z.verification}.\n\nImportant : la carte signale un endroit à regarder. Elle ne prouve pas encore la cause.`}
 function localAnswer(q){const t=clean(q);
  if(/bonjour|salut|bonsoir|hello/.test(t))return `Bonjour. Je suis votre guide AgriVision. Je peux expliquer la carte avec des mots simples et vous dire quoi vérifier, étape par étape.`;
  if(/demain|que dois-je faire|quoi faire|commencer/.test(t))return `Demain matin, faites ceci :\n\n1. Allez d’abord dans la Zone 1.\n2. Prenez un peu de terre à plusieurs endroits et vérifiez si elle est très sèche.\n3. Regardez si les feuilles sont molles, repliées ou flétries.\n4. Visitez ensuite la Zone 2 et observez la couleur des feuilles.\n5. Comparez avec la Zone 3, qui sert de zone de référence.\n\nN’ajoutez pas d’eau ou d’engrais avant cette vérification.`;
  if(/couleur|rouge|jaune|orange|vert|carte/.test(t))return `Rouge signifie priorité forte, jaune signifie à surveiller et vert signifie vigueur élevée. Une couleur n’est pas une maladie : elle indique où vérifier en premier.`;
  if(/humidite.*sans|sans appareil|tester.*terre|sol.*main/.test(t))return `Test simple de l’humidité du sol :\n\n1. Prenez un peu de terre à 5 à 10 cm de profondeur.\n2. Serrez-la doucement dans la main.\n3. Si elle tombe immédiatement en poussière, elle peut être trop sèche.\n4. Si elle forme une boule souple, elle contient encore de l’humidité.\n5. Répétez le test à au moins trois endroits.\n\nCe test est indicatif. Observez aussi les feuilles et les dernières pluies.`;
  if(/resume|synthese|mission/.test(t)&&!/qualite|precision/.test(t))return `Mission du ${mission.date}, parcelle ${mission.parcelle}. Surface classée : ${mission.hectares_analyses} ha. Indice synthétique : ${mission.sante_globale} %. La carte contient ${zoneList.length} zones, dont ${mission.zones_critiques} en priorité forte.`;
  if(/prior|urgence|d'abord|visiter|risque/.test(t)){const order=[...zoneList].sort((a,b)=>({eleve:0,modere:1,faible:2}[a.risque]-{eleve:0,modere:1,faible:2}[b.risque]));return 'Ordre de visite conseillé :\n\n'+order.map((z,i)=>`${i+1}. ${z.nom} — priorité ${z.priorite||z.risque}, contrôle ${z.delai||'à planifier'} : ${z.verification||'observer le sol et les feuilles'}.`).join('\n');}
  if(/zone\s*1/.test(t))return zoneText(zones['zone 1']);if(/zone\s*2/.test(t))return zoneText(zones['zone 2']);if(/zone\s*3/.test(t))return zoneText(zones['zone 3']);
  if(/orthophoto|orthophotographie/.test(t))return `Une orthophoto est une photo prise du ciel puis corrigée pour ressembler à une carte. On peut y mesurer une distance ou retrouver un endroit plus facilement qu’avec une photo ordinaire.`;
  if(/photogram/.test(t))return `La photogrammétrie consiste à assembler beaucoup de photos du drone pour fabriquer une grande image de la zone et, si nécessaire, un modèle en relief.`;
  if(/mns|mnt|modele numerique|relief/.test(t))return `Le MNS représente les hauteurs visibles : sol, plantes, arbres et bâtiments. Le MNT cherche surtout à représenter la hauteur du sol. Ces cartes peuvent aider à comprendre les pentes et l’écoulement de l’eau.`;
  if(/gsd|pixel|1,8|1.8/.test(t))return `Le GSD indique la taille du sol représentée par un pixel. Ici, un pixel représente environ 1,8 centimètre au sol. Cela donne une image détaillée. Mais cela ne veut pas dire que la position GPS est précise à 1,8 centimètre.`;
  if(/vari|ndvi|indice/.test(t))return `Le VARI est un nombre calculé avec les couleurs de la photo.\n\nQuand la valeur est plus élevée, la végétation paraît généralement plus verte ou plus vigoureuse. Quand elle est plus faible, il faut aller vérifier. Le VARI ne dit pas directement s’il manque de l’eau ou de l’engrais. Et ce n’est pas un vrai NDVI.`;
  if(/gps|gcp|precision|erreur/.test(t))return `Le GPS indique où se trouve la carte. Les GCP sont des repères mesurés au sol pour améliorer la précision. Cette mission n’a pas utilisé de GCP. L’erreur rapportée est d’environ 35 centimètres. La carte convient au suivi agricole, pas à une délimitation cadastrale.`;
  if(/azot|engrais|fertili/.test(t))return `Une feuille jaune peut avoir plusieurs causes : manque d’azote, trop d’eau, manque d’eau, maladie ou vieillissement. Comparez d’abord avec la Zone 3 et demandez si possible une analyse du sol. N’appliquez pas d’engrais uniquement parce que la carte est orange.`;
  if(/eau|hydri|irrig/.test(t))return `La Zone 1 peut manquer d’eau, mais il faut le confirmer. Testez la terre à plusieurs endroits, observez les feuilles et vérifiez s’il y a eu de la pluie ou une fuite. Irriguez seulement si le manque d’eau est confirmé.`;
  if(/pourquoi.*sol|verifier.*sol|confirmation/.test(t))return `Le drone voit une différence de couleur, mais plusieurs problèmes peuvent produire la même couleur. La visite au sol permet de connaître la vraie cause avant de dépenser de l’eau, de l’engrais ou un produit.`;
  if(/compost/.test(t))return `Le compost est un mélange de matières végétales et animales décomposées. Un compost prêt est sombre, refroidi et sent la terre. Il ne doit pas être encore très chaud ni sentir fortement la pourriture. Il améliore le sol progressivement, mais ne corrige pas immédiatement un manque d’eau.`;
  if(/paillage|paille|residu/.test(t))return `Le paillage consiste à couvrir la terre avec une couche de pailles ou de résidus de culture sains. Cette couverture protège le sol du soleil et ralentit la perte d’eau. N’utilisez pas des feuilles malades ou très infestées.`;
  if(/legumineuse|graminee|niebe|mucuna|arachide|soja/.test(t))return `Le niébé, le soja, l’arachide et le mucuna sont des légumineuses. Dans une rotation, elles peuvent aider la fertilité du sol. Les graminées protègent le sol et produisent de la paille, mais elles ne fixent généralement pas l’azote.`;
  if(/rotation/.test(t))return `Faire une rotation signifie ne pas planter toujours la même culture au même endroit. Par exemple, après une céréale, on peut planter une légumineuse adaptée. Cela peut réduire certains ravageurs et améliorer progressivement le sol.`;
  if(/neem|bacillus|biologique|bio|chenille|ravageur/.test(t))return `Un produit biologique ne doit être utilisé qu’après avoir vu et identifié le ravageur. Pour certaines chenilles, un produit homologué à base de neem ou de Bacillus thuringiensis peut être envisagé. Respectez toujours l’étiquette, la dose et les protections. Ne traitez pas seulement parce que la carte change de couleur.`;
  if(/limite|fiable|confiance/.test(t))return `AgriVision aide à choisir où regarder. Il ne remplace pas l’agriculteur ni l’agronome. Les limites principales sont le capteur RGB, l’absence de GCP et le fait qu’une seule mission réelle est disponible.`;
  return `Je n’ai pas encore une réponse simple et vérifiée pour cette question. Vous pouvez demander : « Que dois-je faire demain ? », « Explique les couleurs », « Comment vérifier l’humidité ? » ou « Qu’est-ce que le VARI ? »`}
 function context(){const zonesTxt=zoneList.map(z=>`${z.nom}: ${z.surface_ha} ha, VARI ${z.vari}, risque ${z.risque}, causes possibles ${z.causes?.join(', ')||'aucune'}`).join('\n');return `Tu es le guide pédagogique d'AgriVision Bénin. Réponds en français très simple, explique chaque mot scientifique et donne 3 à 5 étapes pratiques. N'invente rien. Mission du ${mission.date}, ${mission.parcelle}, ${mission.hectares_analyses} ha, indice ${mission.sante_globale} %. Zones :\n${zonesTxt}\nLe VARI n'est pas un NDVI. Ne prescris jamais eau, engrais ou pesticide sans vérification au sol.`}
 async function onlineAnswer(q,key){const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+key},body:JSON.stringify({model:'groq/compound-mini',messages:[{role:'system',content:context()},{role:'user',content:q}],temperature:.3,max_tokens:600})});if(!r.ok){ const txt=await r.text(); throw new Error('API '+r.status+' '+txt.slice(0,200)); }const d=await r.json();return d.choices?.[0]?.message?.content||localAnswer(q)}
 async function submit(){const q=input.value.trim();if(!q)return;add('user',q);input.value='';send.disabled=true;const wait=add('bot','Je prépare une explication simple…',true);try{ setBot(wait, localAnswer(q)); }catch(e){ setBot(wait, localAnswer(q)); }finally{send.disabled=false}}
 const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition=null;if(Recognition){recognition=new Recognition();recognition.lang='fr-FR';recognition.interimResults=true;recognition.continuous=false;recognition.onstart=()=>{mic.classList.add('recording');mic.innerHTML='<span class="btn-icon">⏹</span><span class="btn-label">Arrêter</span>';micStatus.textContent='Je vous écoute… Parlez lentement et faites une phrase courte.'};recognition.onresult=e=>{let finalText='',partial='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;e.results[i].isFinal?finalText+=t:partial+=t}input.value=finalText||partial;if(finalText){micStatus.textContent='Phrase entendue : « '+finalText+' »';setTimeout(submit,350)}};recognition.onerror=e=>{micStatus.textContent=e.error==='not-allowed'?'Autorisez le microphone dans le navigateur.':'Je n’ai pas bien compris. Réessayez lentement ou utilisez le clavier.'};recognition.onend=()=>{mic.classList.remove('recording');mic.innerHTML='<span class="btn-icon">🎙️</span><span class="btn-label">Parler</span>'};mic.addEventListener('click',()=>{try{mic.classList.contains('recording')?recognition.stop():recognition.start()}catch(e){}})}else{mic.disabled=true;mic.title='Reconnaissance vocale non disponible sur ce navigateur';micStatus.textContent='La dictée vocale n’est pas disponible sur ce navigateur. Le clavier et la lecture audio restent utilisables.'}
 send.addEventListener('click',submit);input.addEventListener('keydown',e=>{if(e.key==='Enter')submit()});listen.addEventListener('click',()=>lastBot&&speak(lastBot));voiceTest.addEventListener('click',()=>speak('Bonjour. Je suis votre guide AgriVision. Je vais vous expliquer la carte avec des mots simples.'));
 document.getElementById('toggle-glossary')?.addEventListener('click',e=>{const open=document.querySelector('.assistant-main').classList.toggle('glossary-open');e.currentTarget.textContent=open?'✕ Fermer les explications':'📘 Comprendre les mots scientifiques'});document.getElementById('toggle-options')?.addEventListener('click',e=>{const open=document.querySelector('.chat-shell').classList.toggle('options-open');e.currentTarget.textContent=open?'✕ Masquer les options':'🔊 Options de voix'});
 document.querySelectorAll('.suggestion-chip').forEach(b=>b.addEventListener('click',()=>{input.value=b.textContent;submit()}));document.querySelectorAll('.learn-card').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.question;submit()}));
 add('bot',`Bonjour. Je suis votre guide AgriVision. Je peux expliquer les mots scientifiques avec des exemples simples, vous montrer quoi observer et lire mes réponses à voix haute.`);
});
