document.addEventListener('DOMContentLoaded',()=>{
 const file=document.getElementById('qgis-file'),drop=document.getElementById('qgis-drop'),btn=document.getElementById('qgis-import-btn'),msg=document.getElementById('import-message'),bar=document.getElementById('import-progress'),reset=document.getElementById('reset-data');
 const fields={parcelle:document.getElementById('import-parcelle'),date:document.getElementById('import-date'),culture:document.getElementById('import-culture'),photos:document.getElementById('import-photos'),altitude:document.getElementById('import-altitude'),gsd:document.getElementById('import-gsd')};let selected=null;
 const say=(text,type='info')=>{msg.textContent=text;msg.className='import-message '+type;msg.style.display='block'};
 function choose(f){if(!f)return;if(!/\.(geojson|json)$/i.test(f.name))return say('Choisissez un fichier GeoJSON ou JSON.','error');if(f.size>3*1024*1024)return say('Ce fichier dépasse 3 Mo. Exportez une copie simplifiée pour le web depuis QGIS. Le fichier scientifique original reste conservé séparément.','error');selected=f;document.getElementById('selected-file').textContent=`${f.name} · ${(f.size/1024/1024).toFixed(2)} Mo`;say('Fichier prêt. Complétez les informations puis lancez la mise à jour.','ok')}
 file.addEventListener('change',()=>choose(file.files[0]));drop.addEventListener('click',()=>file.click());drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('dragover')});drop.addEventListener('dragleave',()=>drop.classList.remove('dragover'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('dragover');choose(e.dataTransfer.files[0])});
 const normRisk=v=>{const s=String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');if(/eleve|haut|fort|critique/.test(s))return'eleve';if(/faible|bas|sain/.test(s))return'faible';return'modere'};
 const list=v=>Array.isArray(v)?v:(v?String(v).split(/[;,]/).map(x=>x.trim()).filter(Boolean):[]);
 const add=(arr,text)=>{if(!arr.some(x=>x.toLowerCase().includes(text.slice(0,18).toLowerCase())))arr.push(text)};
 function enrich(p){const c=(p.causes||[]).join(' ').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');if(/hydri|eau|secher/.test(c)){add(p.recommandations,'Laisser une couche de pailles ou de résidus sains sur le sol pour ralentir l’évaporation');add(p.recommandations,'Utiliser du compost bien décomposé si le sol en a besoin pour améliorer progressivement la rétention d’eau');add(p.recommandations,'Irriguer seulement après confirmation du manque d’eau, de manière ciblée et tôt le matin')}if(/azot|nutri|carence/.test(c)){add(p.recommandations,'Faire si possible une analyse du sol avant tout apport');add(p.recommandations,'Introduire à la prochaine rotation une légumineuse adaptée : niébé, soja, arachide ou mucuna');add(p.recommandations,'Éviter l’épandage uniforme d’engrais avant confirmation')}if(/chenille|ravageur|insect/.test(c)){add(p.recommandations,'Confirmer la présence du ravageur avant tout traitement');add(p.recommandations,'Si des chenilles sont confirmées, utiliser seulement un produit homologué à base de neem ou de Bacillus thuringiensis selon l’étiquette')}return p}
 function validate(g){if(g?.type!=='FeatureCollection'||!Array.isArray(g.features)||!g.features.length)throw Error('Le fichier doit être une FeatureCollection GeoJSON contenant des zones.');g.features.forEach((f,i)=>{const p=f.properties||{};p.nom=p.nom||`Zone ${i+1}`;p.surface_ha=Number(p.surface_ha||0);p.vari=Number(p.vari??0);p.risque=normRisk(p.risque);p.causes=list(p.causes);p.recommandations=list(p.recommandations);if(!p.recommandations.length)p.recommandations=['Effectuer une vérification terrain avant toute intervention'];p.priorite=p.priorite||(p.risque==='eleve'?'haute':p.risque==='modere'?'moyenne':'faible');p.delai=p.delai||(p.risque==='eleve'?'24 h':p.risque==='modere'?'72 h':'7 jours');p.confiance=p.confiance||'à confirmer sur le terrain';p.verification=p.verification||'Observer le sol et les feuilles';f.properties=enrich(p)});return g}
 function buildMission(g){const z=g.features.map(f=>f.properties),total=z.reduce((s,x)=>s+x.surface_ha,0),part=r=>total?100*z.filter(x=>x.risque===r).reduce((s,x)=>s+x.surface_ha,0)/total:0,weights={faible:100,modere:60,eleve:20},health=total?z.reduce((s,x)=>s+(weights[x.risque]||50)*x.surface_ha,0)/total:0;const current={date:fields.date.value||new Date().toISOString().slice(0,10),date_traitement:new Date().toISOString().slice(0,10),parcelle:fields.parcelle.value.trim()||'Nouvelle parcelle',culture:fields.culture.value.trim()||'À confirmer',hectares_analyses:+total.toFixed(2),parcelles_couvertes:1,zones_critiques:z.filter(x=>x.risque==='eleve').length,zones_surveillance:z.filter(x=>x.risque!=='faible').length,sante_globale:Math.round(health),photos:Number(fields.photos.value)||null,photos_alignees:Number(fields.photos.value)||null,altitude_m:Number(fields.altitude.value)||null,gsd_cm:Number(fields.gsd.value)||null,source:'Import QGIS'};return{derniere_mission:current,repartition:{saine:+part('faible').toFixed(1),stress_leger:+part('modere').toFixed(1),stress_severe:+part('eleve').toFixed(1)}}}
 btn.addEventListener('click',async()=>{if(!selected)return say('Sélectionnez d’abord un fichier GeoJSON.','error');try{btn.disabled=true;bar.style.width='20%';say('Lecture et vérification du fichier…');const text=await selected.text();bar.style.width='48%';const geo=validate(JSON.parse(text));bar.style.width='68%';const mission=buildMission(geo);const savedHistory=localStorage.getItem('agrivision_history');const initialHistory=savedHistory?JSON.parse(savedHistory):[...(MISSIONS_DATA.missions||[])];const history=initialHistory.filter(x=>x.date!==mission.derniere_mission.date);history.push({date:mission.derniere_mission.date,parcelle:mission.derniere_mission.parcelle,score:mission.derniere_mission.sante_globale,reelle:true});history.sort((a,b)=>a.date.localeCompare(b.date));mission.missions=history;// Sauvegarde multi-agriculteur (v18) : garde l'ancien système pour compat + nouveau par farmer
localStorage.setItem('agrivision_geojson',JSON.stringify(geo));localStorage.setItem('agrivision_mission',JSON.stringify(mission));localStorage.setItem('agrivision_history',JSON.stringify(history));
// Nouveau : sauve aussi dans le dictionnaire par agriculteur
try{
  const farmerId = (fields.parcelle.value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'_') || 'parcelle') + '_' + (fields.date.value||new Date().toISOString().slice(0,10));
  const farmerNom = fields.parcelle.value.trim()||'Nouvelle parcelle';
  if(window.AgrivisionSaveFarmer){
    const url = window.AgrivisionSaveFarmer(farmerId, farmerNom, '', mission, geo);
    console.log('Farmer saved', farmerId, url);
  } else {
    const all = JSON.parse(localStorage.getItem('agrivision_farmers')||'{}');
    all[farmerId] = { mission, zones: geo, meta: {nom: farmerNom, parcelle: farmerNom} };
    localStorage.setItem('agrivision_farmers', JSON.stringify(all));
    localStorage.setItem('agrivision_current_farmer', farmerId);
  }
}catch(e){ console.warn('save farmer failed', e); }
bar.style.width='100%';say(`Mise à jour réussie : ${geo.features.length} zones, ${mission.derniere_mission.hectares_analyses} ha, indice ${mission.derniere_mission.sante_globale} %. Ouverture de la carte…`,'ok');setTimeout(()=>location.href='resultats.html',1100)}catch(e){bar.style.width='0';say('Import impossible : '+e.message,'error')}finally{btn.disabled=false}});
 reset.addEventListener('click',()=>{if(confirm('Revenir aux données de démonstration intégrées ?')){localStorage.removeItem('agrivision_geojson');localStorage.removeItem('agrivision_mission');localStorage.removeItem('agrivision_history');say('Données locales supprimées.','ok');setTimeout(()=>location.reload(),500)}});
});